# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mean euclidean distance in parallel
#'
#' @description Computes the mean euclidian distance matrix
#'              for all pairs of samples accross all the features.
#'              This only includes non-missing feature for both pairs.
#'
#'
#' @param y NumericMatrix p x n data matrix
#'
#' @return res list storing Q the n x n unormalized euclidian distance matrix 
#'         and M the n x n matrix storing the number of non-missing features
#'
#' @export
mean_dist <- function(y) {
    .Call('variogramr_mean_dist', PACKAGE = 'variogramr', y)
}

