# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mean euclidean distance for a single pair of observations
#'
#' @description computes the mean euclidian distance
#'              for a single pair of samples all features
#'
#' @param y_i NumericVector p data vector for sample i
#' @param y_j NumericVector p data vector for sample j
#'
#' @return d_ij euclidian distance normalized by number of non-missing
#'         features
#'
#' @export
mean_dist_pair <- function(y_i, y_j) {
    .Call('variogramr_mean_dist_pair', PACKAGE = 'variogramr', y_i, y_j)
}

#' @title Mean euclidean distance
#'
#' @description Computes the mean euclidian distance matrix
#'              for all pairs of samples accross all the features.
#'              This only includes non-missing feature for both pairs.
#'
#'
#' @param y NumericMatrix n x p data matrix
#'
#' @return d n x n euclidian distance matrix
#'
#' @export
mean_dist <- function(y) {
    .Call('variogramr_mean_dist', PACKAGE = 'variogramr', y)
}

